v1 readme
brown-cs1380/m5 pull request #1
Opened 2024-04-02 20:39 UTC by tonyzhu163

draft 1 of markdown handout

2024-04-03 12:46 UTC, nvasilakis requested changes
This looks great! Minor changes requested, thanks!

2024-04-03 12:46 UTC, nvasilakis commented on docs/README.md
> +- Background & Context
These are not links to the document, are they?

2024-04-03 12:46 UTC, nvasilakis commented on docs/README.md
> +| mr  | A MapReduce implementation    |   **exec**     |
`exec` with backquotes, not **exec** using bold:-)

2024-04-03 12:46 UTC, nvasilakis commented on docs/README.md
> +```
We might want to add a FAQ section here.

2024-04-04 19:54 UTC, tonyzhu163 commented
@nvasilakis 

Resolved changes mentioned.

2024-04-04 22:42 UTC, nvasilakis approved these changes

2024-04-04 22:42 UTC, merged